export const dataParam = [
    { title: 'Chiến Tranh', to: 'chien-tranh' },
    { title: 'Viễn Tưởng', to: 'vien-tuong' },
    { title: 'Hài Hước', to: 'hai-huoc' },
    { title: 'Hành Động', to: 'hanh-dong' },
    { title: 'Phiêu Lưu', to: 'phieu-luu' },
    { title: 'Hình Sự', to: 'hinh-su' },
    { title: 'Bí ẩn', to: 'bi-an' },
    { title: 'Tình Cảm', to: 'tinh-cam' },
    { title: 'Kinh Dị', to: 'kinh-di' },
    { title: 'Tài Liệu', to: 'tai-lieu' },
    { title: 'Tâm Lý', to: 'tam-ly' },
    { title: 'Võ Thuật', to: 'vo-thuat' },
    { title: 'Học Đường', to: 'hoc-duong' },
    { title: 'Gia Đình', to: 'gia-dinh' },
    { title: 'Cổ Trang', to: 'co-trang' },
    { title: 'Khoa Học', to: 'khoa-hoc' },
    { title: 'Âm Nhạc', to: 'am-nhac' },
    { title: 'Thể Thao', to: 'the-thao' },
    { title: 'Kinh Điển', to: 'kinh-dien' },
    { title: 'Thần Thoại', to: 'than-thoai' },
    { title: 'Chính Kịch', to: 'chinh-kich' },
    { title: 'Quốc Gia Khác', to: 'quoc-gia-khac' },
    { title: 'Âu Mỹ', to: 'au-my' },
    { title: 'Hồng Kông', to: 'hong-kong' },
    { title: 'Nhật Bản', to: 'nhat-ban' },
    { title: 'Thái Lan', to: 'thai-lan' },
    { title: 'Trung Quốc', to: 'trung-quoc' },
    { title: 'Hàn Quốc', to: 'han-quoc' },
    { title: 'Phim Bộ', to: 'phim-bo' },
    { title: 'Phim Lẻ', to: 'phim-le' },
    { title: 'Phim Mới', to: 'phim-moi' },
];
