const listDatabM = [
    {
        image: 'https://phim1080y.com/storage/images/cuoc-chien-thua-ke-poster.webp',
        path: '/cuoc-chien-thua-ke',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'CUỘC CHIẾN THỪA KẾ',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
                {
                    chapterName: 'tập 2',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'flase',
                },
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'flase',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/nguoi-mexico-thumb.webp',
        path: '/tro-choi-kim-tu-thap',

        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
                {
                    chapterName: 'tập 2',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'flase',
                },
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'flase',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/phia-tay-memphis-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/polis-evo-3-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
                {
                    chapterName: 'tập 2',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'flase',
                },
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'flase',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/sau-con-say-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
            ],
        },
    },
];
const listDataHH = [
    {
        image: 'https://phim1080y.com/storage/images/ke-hoach-du-phong-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/ke-hoach-du-phong-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
                {
                    chapterName: 'tập 2',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'flase',
                },
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'flase',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/phia-tay-memphis-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/polis-evo-3-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
                {
                    chapterName: 'tập 2',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'flase',
                },
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'flase',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/sau-con-say-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
            ],
        },
    },
];
const listDataDC = [
    {
        image: 'https://phim1080y.com/storage/images/cuoc-chien-thua-ke-poster.webp',
        path: '/cuoc-chien-thua-ke',
        des: {
            nation: 'Hàn Quốc',
            quality: 'HD',
            point: '8.0/10',
            title: 'CUỘC CHIẾN THỪA KẾ',
            name: 'Pyramid Game',
            char: ' Lee Jae-wook, Lee Jun-young, Hong Su-zu, Lee Ji-hoon, Lee Hwang-eui, Han Sang-jin',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            filmDescription:
                'Khi đứa con ngoài giá thú của một chủ tập đoàn Hàn Quốc hợp tác với người bạn thời thơ ấu đầy tham vọng của mình, bộ đôi này sẽ không ngừng nỗ lực để giành lấy vị trí đứng đầu chuỗi thức ăn xã hội. Sinh ra trong một gia đình đơn thân nghèo khó, chẳng có gì ngoài vẻ ngoài điển trai và sự quyến rũ, Kang In Ha luôn khao khát thành công. Quyết tâm làm nên điều gì đó cho riêng mình, bất kể giá nào, In Ha phát hiện ra rằng cha mình là chủ tịch của Tập đoàn Kang Oh cực kỳ thành công và bỏ lại cuộc sống nghèo khó phía sau. Bị những người còn lại trong gia đình mới xa lánh, In Ha hợp tác với người bạn có năng khiếu trí tuệ Han Tae Oh, ấp ủ kế hoạch từ khi còn trẻ để tiếp quản công ty và giành lấy vị trí đứng đầu xã hội của họ. Nhận ra thành công từ rất sớm, cặp đôi bắt đầu đi lên đều đặn cho đến khi một người phụ nữ đầy tham vọng không kém với quá khứ rắc rối tương tự đe dọa làm hỏng kế hoạch của họ mãi mãi.',
            chapters: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=Ok5PXdmQV-s',
                    isplaying: 'true',
                },
                {
                    chapterName: 'tập 2',
                    pathVideo: 'https://www.youtube.com/watch?v=uC9qU3X1JgM',
                    isplaying: 'flase',
                },
                {
                    chapterName: 'tập 3',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'flase',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/tro-choi-kim-tu-thap-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            nation: 'Hàn Quốc',
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/tro-choi-kim-tu-thap-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/tro-choi-kim-tu-thap-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/tro-choi-kim-tu-thap-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/tro-choi-kim-tu-thap-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/tro-choi-kim-tu-thap-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/tro-choi-kim-tu-thap-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/tro-choi-kim-tu-thap-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
        },
    },
];
const listDataCN = [
    {
        image: 'https://phim1080y.com/storage/images/chuyen-tinh-cua-anh-chi-em-toi-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/boa-cat-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/tim-duong-ve-nha-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/cam-on-em-da-suoi-am-anh-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/tan-thieu-nien-bao-chung-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/anikulapo-bong-ma-troi-day-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/ara-san-juan-chiec-tau-ngam-mat-tich-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
            ],
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/chao-mung-den-voi-lop-hoc-de-cao-thuc-luc-phan-2-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/chuong-trinh-dieu-chinh-hanh-vi-thieu-nien-nhung-goc-khuat-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/tin-hieu-bi-mat-tu-khong-gian-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/nu-hoang-nuoc-mat-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/cau-chuyen-ve-indrani-mukerjea-su-that-bi-chon-giau-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            chapter: [
                {
                    chapterName: 'tập 1',
                    pathVideo: 'https://www.youtube.com/watch?v=GV3HUDMQ-F8',
                    isplaying: 'true',
                },
            ],
        },
    },
];
const listDataXH = [
    {
        image: 'https://phim1080y.com/storage/images/ke-hoach-du-phong-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/ke-hoach-du-phong-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/phia-tay-memphis-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/polis-evo-3-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/sau-con-say-thumb.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
];
const listDataCS = [
    {
        image: 'https://phim1080y.com/storage/images/tiem-chup-anh-ma-quai-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/love-senior-tien-boi-ky-luat-yeu-em-duoc-khong-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/ti-thua-dai-nhan-than-yeu-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/the-gioi-ngam-tokyo-phan-2-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/alexander-dai-de-tao-nen-mot-vi-than-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/mau-lanh-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
    {
        image: 'https://phim1080y.com/storage/images/exhuma-quat-mo-trung-ma-poster.webp',
        path: '/tro-choi-kim-tu-thap',
        des: {
            quality: 'HD',
            point: '8.0/10',
            title: 'Trò Chơi Kim Tự Tháp',
            name: 'Pyramid Game',
            views: '1k xem',
            likes: 'Tập 6',
            audio: 'vietsub',
        },
    },
];
export { listDatabM, listDataHH, listDataDC, listDataCN, listDataXH, listDataCS };
